channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow>=2.0.0
      - cloudpickle>=2.0.0
      - numpy>=1.20.0
      - pandas>=1.3.0
      - scikit-learn>=1.0.0
      - scipy>=1.7.0
name: mlflow-env
