channels:
  - conda-forge
dependencies:
  - python=3.10.0
  - pip<=21.2.3
  - pip:
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - numpy==2.2.6
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
name: mlflow-env
