name: CI Workflow for ML Model - Kriteria 3 Advanced

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_train_deploy_model:
    name: Build, Train, and Deploy ML Model
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MLflow CLI
        run: pip install mlflow scikit-learn

      - name: 3. Check Environment
        run: |
          python --version
          pip --version
          mlflow --version

      - name: 4. Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          python-version: '3.10.6'
          auto-activate-base: false

      - name: 5. Run MLflow Project
        shell: bash -l {0}
        run: |
          echo "Starting MLflow project run..."
          cd MLProject
          mlflow run . --experiment-name "Lung_Cancer_CI_Run"
          echo "MLflow project run finished."
          # Pastikan mlflow_run_id.txt dibuat di dalam MLProject/
          if [ ! -f mlflow_run_id.txt ]; then
            echo "Error: mlflow_run_id.txt was not created by modeling.py in MLProject/"
            ls -la # Tampilkan isi direktori untuk debugging
            exit 1
          fi
          cd $GITHUB_WORKSPACE

      - name: 6. Get MLflow Run ID
        id: get_run_id
        run: |
          # Pastikan file ada sebelum mencoba membacanya
          if [ ! -f MLProject/mlflow_run_id.txt ]; then
            echo "Error: MLProject/mlflow_run_id.txt not found in Get MLflow Run ID step."
            ls -la MLProject/ # Tampilkan isi direktori MLProject untuk debugging
            exit 1
          fi
          RUN_ID_VALUE=$(cat MLProject/mlflow_run_id.txt)
          echo "Raw Run ID from file: $RUN_ID_VALUE"
          CLEANED_RUN_ID=$(echo -n $RUN_ID_VALUE | tr -d '[:space:]')
          echo "Cleaned Run ID: $CLEANED_RUN_ID"
          echo "run_id_value=$CLEANED_RUN_ID" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}

      - name: 7. Upload MLflow Run Artifacts (mlruns)
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-output
          # Path harus benar relatif dari GITHUB_WORKSPACE
          path: ${{ github.workspace }}/MLProject/mlruns/
          if-no-files-found: warn

      - name: Upload mlflow_run_id.txt
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-id-file
          path: ${{ github.workspace }}/MLProject/mlflow_run_id.txt
          if-no-files-found: warn

      - name: 8. Build Docker Image with MLflow
        env:
          MLFLOW_RUN_ID: ${{ steps.get_run_id.outputs.run_id_value }}
          # Tambahkan MLFLOW_TRACKING_URI untuk menunjuk ke direktori mlruns lokal
          MLFLOW_TRACKING_URI: file://${{ github.workspace }}/MLProject/mlruns
        run: |
          echo "Building Docker image for Run ID: $MLFLOW_RUN_ID"
          echo "Using MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI"
          
          if [ -z "$MLFLOW_RUN_ID" ]; then
            echo "Error: MLFLOW_RUN_ID is empty. Cannot build Docker image."
            exit 1
          fi
          
          # Ganti 'yaqin7' dengan username Docker Hub-mu
          # Ganti 'lung-cancer-model' dengan nama repositori Docker Hub-mu
          DOCKER_IMAGE_NAME="yaqin7/lung-cancer-model:${{ github.sha }}"
          echo "Target Docker Image Name: $DOCKER_IMAGE_NAME"
          
          mlflow models build-docker \
            --model-uri "runs:/$MLFLOW_RUN_ID/model" \
            --name "$DOCKER_IMAGE_NAME" \
            --enable-mlserver
          
          echo "Docker image build process initiated for $DOCKER_IMAGE_NAME"

      - name: 9. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 10. Push Docker Image to Docker Hub
        run: |
          # Ganti 'fahmi123zul' dengan username Docker Hub-mu
          # Ganti 'breast-cancer-model' dengan nama repositori Docker Hub-mu
          DOCKER_IMAGE_NAME="yaqin7/lung-cancer-model:${{ github.sha }}"
          echo "Pushing Docker Image: $DOCKER_IMAGE_NAME"
          docker push $DOCKER_IMAGE_NAME
          echo "Docker Image pushed."

      - name: 11. Log out from Docker Hub
        if: always()
        run: docker logout
